id: A1137F1F7
title: Longevity Practice for the Peaceful and Wrathful Deities of Droltik
type: translation
pechas:
- I99EDE6C1
- I20D67A07
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:34:17.991106
  last_modified_at: 2023-01-04 12:34:17.991111
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I99EDE6C1/AC94: F4B2
  I20D67A07/4309: F4B2
